-- MySQL Script generated by MySQL Workbench
-- Fri 14 Oct 2016 19:24:07 AEDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema infs3605
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `infs3605` ;

-- -----------------------------------------------------
-- Schema infs3605
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infs3605` DEFAULT CHARACTER SET utf8 ;
USE `infs3605` ;

-- -----------------------------------------------------
-- Table `infs3605`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`user` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `type` VARCHAR(45) NOT NULL,
  `loginAttempt` INT(1) NOT NULL,
  `locked` TINYINT(1) NOT NULL,
  `unlockCode` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infs3605`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`course` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`course` (
  `courseId` INT NOT NULL AUTO_INCREMENT,
  `courseCode` VARCHAR(8) NULL,
  `courseName` VARCHAR(100) NULL,
  `uoc` VARCHAR(2) NULL,
  PRIMARY KEY (`courseId`))
ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8;

LOCK TABLES `course` WRITE;

INSERT INTO `course` VALUES
(1, 'INFS1602', 'Digital Transformation in Business', '6'), 
(2, 'INFS1603', 'Introduction to Business Databases', '6'), 
(3, 'INFS1609', 'Fundamentals of Business Programming', '6'),
(4, 'INFS2101', 'Industry Placement 1', '12'), 
(5, 'INFS2603', 'Business Analysis using Design Thinking', '6'), 
(6, 'INFS2605', 'Intermediate Business Programming', '6'),
(7, 'INFS2607', 'Networking and Infrastructure', '6'),
(8, 'INFS2608', 'Database Management & Big Data Infrastructures', '6'),
(9, 'INFS2609', 'Programming for Business', '6'),
(10, 'INFS2621', 'Enterprise Systems', '6'),
(11, 'INFS2631', 'Innovation and Technology Management', '6'),
(12, 'INFS2848', 'Information Systems Project Management', '6'),
(13, 'INFS3020', 'International Info. Sys. and Technology Practicum', '6'),
(14, 'INFS3202', 'Industry Placement 2', '12'),
(15, 'INFS3303', 'Industry Placement 3', '12'),
(16, 'INFS3603', 'Introduction to Business Analytics', '6'),
(17, 'INFS3604', 'Business Process Management', '6'),
(18, 'INFS3605', 'Information Systems Innovation & Transformation', '6'),
(19, 'INFS3611', 'Information Systems Project 1', '6'),
(20, 'INFS3617', 'Networking & Cyber Security', '6'),
(21, 'INFS3631', 'Innovation and Technology Management', '6'),
(22, 'INFS3632', 'Service and Quality Management', '6'),
(23, 'INFS3633', 'Information Systems Sourcing', '6'),
(24, 'INFS3634', 'Mobile Applications Development', '6'),
(25, 'INFS3692', 'Internship 1', '12'),
(26, 'INFS3774', 'Information Systems Security', '6'),
(27, 'INFS3792', 'Industrial Training B', '12'),
(28, 'INFS3830', 'Social Media and Analytics', '6'),
(29, 'INFS3873', 'Business Analytics Methods', '6'),
(30, 'INFS4693', 'Internship 2', '12'),
(31, 'INFS4793', 'Industrial Training C', '12'),
(32, 'INFS4795', 'Thesis Part A', '6'),
(33, 'INFS4796', 'Thesis Part B', '18'),
(34, 'INFS4805', 'Information Systems Auditing and Assurance', '6'),
(35, 'INFS4830', 'Social Media and Networking', '6'),
(36, 'INFS4831', 'Information Systems Consulting', '6'),
(37, 'INFS4833', 'Contemporary Challenges in Information Systems', '6'),
(38, 'INFS4854', 'Information Systems Strategy', '6'),
(39, 'INFS4858', 'Project, Portfolio and Program Management', '6'),
(40, 'INFS4885', 'e-Business Applications and Technologies', '6'),
(41, 'INFS4886', 'Principles of Research Design', '6'),
(42, 'INFS4887', 'Business Research Methods', '6'),
(43, 'INFS4893', 'Special Topic in Information Systems', '6'),
(44, 'INFS4907', 'Managing Security and Ethics in Cyberspace', '6');

UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `infs3605`.`program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`program` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`program` (
  `programId` INT NOT NULL AUTO_INCREMENT,
  `programCode` VARCHAR(5) NOT NULL,
  `programName` VARCHAR(100) NOT NULL,
  `handbookYear` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`programId`))
ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8;


LOCK TABLES `program` WRITE;

INSERT INTO `program` VALUES
(1, '3589', 'Actuarial Stu/Adv Maths (Hons)', '2017'),		/* BUSINESS FACULTY */
(2, '3586', 'Actuarial Studies', '2017'),
(3, '3587', 'Actuarial Studies (Co-op)', '2017'),
(4, '4520', 'Actuarial Studies (Honours)', '2017'),
(5, '3155', 'Actuarial Studies / Commerce', '2017'),
(6, '3588', 'Actuarial Studies / Economics', '2017'),
(7, '3154', 'Actuarial Studies / Science', '2017'),
(8, '3523', 'Advanced Maths (Hons)/Commerce', '2017'),
(9, '3964', 'BIS (Co-op) (Hons)', '2017'),
(10, '3502', 'Commerce', '2017'),
(11, '3964', 'Commerce (Co-op)', '2017'),
(12, '3565', 'Commerce (Co-op) (Hons)', '2017'),
(13, '4501', 'Commerce (Honours)', '2017'),
(14, '3558', 'Commerce (International)', '2017'),
(15, '3573', 'Commerce / Arts', '2017'),
(16, '3835', 'Commerce / Aviation (Mgmt)', '2017'),
(17, '3967', 'Commerce / Computer Science', '2017'),
(18, '3568', 'Commerce / Design (Honours)', '2017'),
(19, '3567', 'Commerce / Fine Arts', '2017'),
(20, '3584', 'Commerce / Information Systems', '2017'),
(21, '3593', 'Commerce/Adv Science (Hons)', '2017'),
(22, '3521', 'Commerce/Economics', '2017'),
(23, '3559', 'Commerce/Media (PR & Advert)', '2017'),
(24, '3529', 'Commerce/Science', '2017'),
(25, '3543', 'Economics', '2017'),
(26, '4502', 'Economics (Honours)', '2017'),
(27, '3574', 'Economics / Arts', '2017'),
(28, '3563', 'Economics / Science', '2017'),
(29, '3566', 'Economics/Adv Science (Hons)', '2017'),
(30, '3564', 'Economics/Advanced Maths(Hons)', '2017'),
(31, '3979', 'Information Systems', '2017'),					
(32, '3736', 'BE (Hons) ME Elec Eng', '2017'),				/* ENGINEERING FACULTY */
(33, '3731', 'BE ME Electrical Engineering', '2017'),
(34, '3631', 'Civil Eng/Environmental Eng', '2017'),
(35, '3146', 'Civil Eng/Mining Eng', '2017'),
(36, '4515', 'Computer Sci & Eng (Honours)', '2017'),
(37, '3978', 'Computer Science', '2017'),
(38, '3963', 'Computer Science / Arts', '2017'),
(39, '3968', 'Computer Science / Arts', '2017'),
(40, '3635', 'Eng (Civil w Arch) (Hons)', '2017'),
(41, '3773', 'Eng (Hons) / Eng Science', '2017'),
(42, '3707', 'Engineering (Honours)', '2017'),
(43, '3763', 'Engineering (Honours) / Arts', '2017'),
(44, '3961', 'Engineering (Honours) / Arts', '2017'),
(45, '3767', 'Engineering (Hons) / Science', '2017'),
(46, '3776', 'Engineering (Hons) / Surveying', '2017'),
(47, '3768', 'Engineering (Hons)/Biomed Eng', '2017'),
(48, '3764', 'Engineering (Hons)/Commerce', '2017'),
(49, '3772', 'Engineering(Hons)/Computer Sci', '2017'),
(50, '3065', 'Food Science', '2017'),
(51, '3061', 'Food Science (Honours)', '2017'),
(52, '3969', 'Media Arts (Hons) / Comp Sci', '2017'),
(53, '3983', 'Science/Computer Science', '2017');

UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `infs3605`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`student` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`student` (
  `studentId` INT NOT NULL AUTO_INCREMENT,
  `zId` VARCHAR(8) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `programId` INT NOT NULL,
  `privEmail` VARCHAR(45) NULL,
  `privPhone` VARCHAR(45) NULL,
  `workPhone` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `currentWam` VARCHAR(45) NULL,
  `yearEnrolled` VARCHAR(4) NULL,
  `type` VARCHAR(45) NOT NULL,
  `ip1` VARCHAR(100) NULL,
  `ip2` VARCHAR(100) NULL,
  `ip3` VARCHAR(100) NULL,
  PRIMARY KEY (`studentId`),
  INDEX `fk_student_program_idx` (`programId` ASC),
  CONSTRAINT `fk_student_program`
    FOREIGN KEY (`programId`)
    REFERENCES `infs3605`.`program` (`programId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infs3605`.`enrolment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`enrolment` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`enrolment` (
  `courseId` INT NOT NULL,
  `studentId` INT NOT NULL,
  `mark` INT NOT NULL,
  `semYear` VARCHAR(45) NOT NULL,
  INDEX `fk_course_id_idx` (`courseId` ASC),
  INDEX `fk_student_id_idx` (`studentId` ASC),
  CONSTRAINT `fk_enrol_course`
    FOREIGN KEY (`courseId`)
    REFERENCES `infs3605`.`course` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enrol_student`
    FOREIGN KEY (`studentId`)
    REFERENCES `infs3605`.`student` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infs3605`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`booking` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`booking` (
  `bookingId` INT NOT NULL AUTO_INCREMENT,
  `zId` VARCHAR(8) NOT NULL,
  `category` VARCHAR(30) NOT NULL,
  `startDate` VARCHAR(20) NOT NULL,
  `endDate` VARCHAR(20) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `priority` INT NOT NULL,
  PRIMARY KEY (`bookingId`));


-- -----------------------------------------------------
-- Table `infs3605`.`bookingList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`bookingList` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`bookingList` (
  `bookingId` INT NOT NULL,
  `studentId` INT NOT NULL,
  `userId` INT NOT NULL,
  INDEX `fk_student_id_idx` (`studentId` ASC),
  INDEX `fk_coordinator_id_idx` (`userId` ASC),
  INDEX `fk_bookingList_booking_id_idx` (`bookingId` ASC),
  CONSTRAINT `fk_bookingList_student_id`
    FOREIGN KEY (`studentId`)
    REFERENCES `infs3605`.`student` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookingList_coordinator_id`
    FOREIGN KEY (`userId`)
    REFERENCES `infs3605`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookingList_booking_id`
    FOREIGN KEY (`bookingId`)
    REFERENCES `infs3605`.`booking` (`bookingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infs3605`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`note` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`note` (
  `noteId` INT NOT NULL AUTO_INCREMENT,
  `texts` VARCHAR(255) NOT NULL,
  `dateCreated` VARCHAR(20) NOT NULL,
  `bookingId` INT NOT NULL,
  PRIMARY KEY (`noteId`),
  INDEX `fk_note_booking_idx` (`bookingId` ASC),
  CONSTRAINT `fk_note_booking`
    FOREIGN KEY (`bookingId`)
    REFERENCES `infs3605`.`booking` (`bookingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infs3605`.`Lecturing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`Lecturing` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`Lecturing` (
  `userId` INT NOT NULL,
  `courseId` INT NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  INDEX `fk_Lecturing_coord_idx` (`userId` ASC),
  INDEX `fk_Lecturing_course_idx` (`courseId` ASC),
  CONSTRAINT `fk_lecturing_coord`
    FOREIGN KEY (`userId`)
    REFERENCES `infs3605`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecturing_course`
    FOREIGN KEY (`courseId`)
    REFERENCES `infs3605`.`course` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `infs3605`.`sponsors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`sponsors` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`sponsors` (
  `sponsorId` INT NOT NULL AUTO_INCREMENT,
  `sponsorName` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`sponsorId`));


-- -----------------------------------------------------
-- Table `infs3605`.`preferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`preferences` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`preferences` (
  `preferenceId` INT NOT NULL AUTO_INCREMENT,
  `studentId` INT NOT NULL,
  `firstPref` INT NULL,
  `secondPref` INT NULL,
  `thirdPref` INT NULL,
  `fourthPref` INT NULL,
  `fifthPref` INT NULL,
  `sixthPref` INT NULL,
  `IPLevel` VARCHAR(20) NULL,
  INDEX `fk_preferences_studentId_idx` (`studentId` ASC),
  PRIMARY KEY (`preferenceId`),
  INDEX `fk_preferences_1_idx` (`firstPref` ASC),
  INDEX `fk_preferences_2_idx` (`secondPref` ASC),
  INDEX `fk_preferences_3_idx` (`thirdPref` ASC),
  INDEX `fk_preferences_5_idx` (`fifthPref` ASC),
  INDEX `fk_preferences_6_idx` (`sixthPref` ASC),
  CONSTRAINT `fk_preferences_studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `infs3605`.`student` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferences_1`
    FOREIGN KEY (`firstPref`)
    REFERENCES `infs3605`.`sponsors` (`sponsorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferences_2`
    FOREIGN KEY (`secondPref`)
    REFERENCES `infs3605`.`sponsors` (`sponsorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferences_3`
    FOREIGN KEY (`thirdPref`)
    REFERENCES `infs3605`.`sponsors` (`sponsorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferences_4`
    FOREIGN KEY (`fourthPref`)
    REFERENCES `infs3605`.`sponsors` (`sponsorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferences_5`
    FOREIGN KEY (`fifthPref`)
    REFERENCES `infs3605`.`sponsors` (`sponsorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferences_6`
    FOREIGN KEY (`sixthPref`)
    REFERENCES `infs3605`.`sponsors` (`sponsorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `infs3605`.`offenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`offenses` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`offenses` (
  `offenseId` INT NOT NULL AUTO_INCREMENT,
  `studentId` INT NOT NULL,
  `offenseName` VARCHAR(45) NULL,
  `dateCommitted` VARCHAR(45) NULL,
  PRIMARY KEY (`offenseId`),
  INDEX `fk_category_studentId_idx` (`studentId` ASC),
  CONSTRAINT `fk_category_studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `infs3605`.`student` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `infs3605`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`events` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(127) NOT NULL,
  `start_date` VARCHAR(20) NOT NULL,
  `end_date` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infs3605`.`attendee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infs3605`.`attendee` ;

CREATE TABLE IF NOT EXISTS `infs3605`.`attendee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bookingId` INT NOT NULL,
  `studentId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attendee_1_idx` (`bookingId` ASC),
  INDEX `fk_attendee_2_idx` (`studentId` ASC),
  CONSTRAINT `fk_attendee_1`
    FOREIGN KEY (`bookingId`)
    REFERENCES `infs3605`.`booking` (`bookingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendee_2`
    FOREIGN KEY (`studentId`)
    REFERENCES `infs3605`.`student` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
